# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
steps:
- task: CredScan@3
  displayName: 'Run CredScan'
  inputs:
    debugMode: false
    batchSize: 20
    toolMajorVersion: 'V2'
    searchersFileType: 'Skype'

- task: PoliCheck@2
  displayName: 'Run PoliCheck'
  condition: and(succeeded(), eq(eq(variables['Build.SourceBranch'], 'refs/heads/main'), false))
  inputs:
    targetType: F
    SOMEnabled: true
    optionsFC: 0
    optionsXS: 0
    optionsHMENABLE: 0
    continueOnError: true