# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
  displayName: 'Run CredScan - Src'
  inputs:
    debugMode: false
    scanFolder: '$(Build.SourcesDirectory)\src'
    toolMajorVersion: 'V2'

- task: PoliCheck@2
  displayName: 'Run PoliCheck'
  condition: and(succeeded(), eq(eq(variables['Build.SourceBranch'], 'refs/heads/main'), false))
  inputs:
    targetType: F
    SOMEnabled: true
    optionsFC: 0
    optionsXS: 0
    optionsHMENABLE: 0
    continueOnError: true