# Microsoft Graph PowerShell AutoRest Configuration
powershell: true
version: latest
use: "@autorest/powershell@latest"
module-version: 0.1.0
subject-prefix: ""
license-header: © Microsoft Corporation. All rights reserved.
azure: false
module-name: $(ModuleNamespace).$(title)
namespace: Microsoft.Graph.PowerShell
input-file: $(DocOutputFolder)\$(title).yml
output-folder: ..\src\$(GraphVersion)\$(title)\$(title)
clear-output-folder: true
use-internal-constructors: true
use-datetimeoffset : true
#sanitize-names: true
metadata:
  authors: Microsoft
  description: Microsoft Graph PowerShell module
  companyName: Microsoft
  owners: Microsoft
  requireLicenseAcceptance: true
  copyright: © Microsoft Corporation. All rights reserved.
  licenseUri: https://aka.ms/devservicesagreement
  projectUri: https://github.com/microsoftgraph/msgraph-sdk-powershell
  iconUri: https://raw.githubusercontent.com/microsoftgraph/g-raph/master/g-raph.png
  tags: Microsoft;Office365;Graph;PowerShell;GraphServiceClient;Outlook;OneDrive;AzureAD;GraphAPI;Productivity;SharePoint;Intune;SDK;
directive:
# GroupMemberOf
  - where:
      verb: Get
      subject: GroupMember
      variant: Get1
    set:
      subject: GroupMemberOf
  - where:
      verb: Get
      subject: GroupMember
      variant: List
    set:
      subject: GroupMemberOf
  - where:
      verb: Get
      subject: GroupMember
      variant: GetViaIdentity1
    set:
      subject: GroupMemberOf
# GroupMemberWithLicenseError
  - where:
      verb: Get
      subject: GroupMember
      variant: Get
    set:
      subject: GroupMemberWithLicenseError
  - where:
      verb: Get
      subject: GroupMember
      variant: List2
    set:
      subject: GroupMemberWithLicenseError
  - where:
      verb: Get
      subject: GroupMember
      variant: GetViaIdentity
    set:
      subject: GroupMemberWithLicenseError
# GroupTransitiveMemberOf
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: List
    set:
      subject: GroupTransitiveMemberOf
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: Get
    set:
      subject: GroupTransitiveMemberOf
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: GetViaIdentity
    set:
      subject: GroupTransitiveMemberOf
  - no-inline: # tells it not to inline the model with that name 
    - microsoft.graph.sharepointIds
    - microsoft.graph.identitySet
    - microsoft.graph.itemReference
    - microsoft.graph.directoryObject