# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

#AutoRest PowerShell Config File
subject-prefix: ''
module-version: 0.0.1
clear-output-folder: true
namespace: Microsoft.Graph
license-header: MICROSOFT_MIT_NO_VERSION
# directive:
#   - where:
#       subject: Me(.*)
#     set:
#       subject: My$1