# Microsoft Graph PowerShell AutoRest Configuration
powershell: true
version: latest
use: '@microsoft.azure/autorest.powershell@2.0.648'
module-version: 0.1.0
# prefix: Graph
subject-prefix: ''
azure: false
# module-name: $(prefix).$(title)
module-name: $(rollUpModule).$(title)
namespace: Microsoft.Graph.PowerShell
input-file: $(docOutputFolder)\$(title).yml
output-folder: ..\src\$(title)\$(title)
clear-output-folder: true
metadata:
  authors: Microsoft
  description: Microsoft Graph PowerShell module
  companyName: Microsoft
  requireLicenseAcceptance: false
  copyright: © Microsoft Corporation. All rights reserved.
  licenseUrl: https://aka.ms/devservicesagreement
  projectUrl: https://github.com/microsoftgraph/msgraph-sdk-powershell
  iconUrl: https://raw.githubusercontent.com/microsoftgraph/g-raph/master/g-raph.png
  tags: Microsoft;Office365;Graph;PowerShell;GraphServiceClient;Outlook;OneDrive;AzureAD;GraphAPI;Productivity;SharePoint;Intune;SDK;
# directive:
#   - where:
#       subject: Me(.*)
#     set:
#       subject: My$1
directive: 
 - no-inline:
   - microsoft.graph.sharepointIds  # tells it not to inline the model with that name 
   - microsoft.graph.identitySet
