# Microsoft Graph PowerShell AutoRest Configuration
powershell: true
version: latest
use: "@autorest/powershell@latest"
module-version: 0.1.0
subject-prefix: ""
license-header: © Microsoft Corporation. All rights reserved.
azure: false
module-name: $(ModuleNamespace).$(title)
namespace: Microsoft.Graph.PowerShell
input-file: $(DocOutputFolder)\$(title).yml
output-folder: ..\src\$(GraphVersion)\$(title)\$(title)
clear-output-folder: true
use-internal-constructors: true
use-datetimeoffset : true
#sanitize-names: true
metadata:
  authors: Microsoft
  description: Microsoft Graph PowerShell module
  companyName: Microsoft
  owners: Microsoft
  requireLicenseAcceptance: true
  copyright: © Microsoft Corporation. All rights reserved.
  licenseUri: https://aka.ms/devservicesagreement
  projectUri: https://github.com/microsoftgraph/msgraph-sdk-powershell
  iconUri: https://raw.githubusercontent.com/microsoftgraph/g-raph/master/g-raph.png
  tags: Microsoft;Office365;Graph;PowerShell;GraphServiceClient;Outlook;OneDrive;AzureAD;GraphAPI;Productivity;SharePoint;Intune;SDK;
directive:
  - no-inline: # tells it not to inline the model with that name 
    - microsoft.graph.sharepointIds
    - microsoft.graph.identitySet
    - microsoft.graph.itemReference
    - microsoft.graph.directoryObject
    - microsoft.graph.user
    - microsoft.graph.drive
    - microsoft.graph.listItem
    - microsoft.graph.post
    - microsoft.graph.sectionGroup
    - microsoft.graph.team
  - where:
      model-name: MicrosoftGraphUser
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - Mail
          - UserPrincipalName
          - UserType
  - where:
      model-name: MicrosoftGraphPerson
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - MailboxType
          - PersonType
          - IsFavorite
  - where:
      model-name: MicrosoftGraphContact
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - EmailAddresses
          - Phones
          - CreatedDateTime
  - where:
      model-name: MicrosoftGraphCalendar
    set:
      format-table:
        properties:
          - Id
          - Name
          - OwnerName
          - OwnerAddress
  - where:
      model-name: MicrosoftGraphEvent
    set:
      format-table:
        properties:
          - Id
          - Subject
          - StartDateTime
          - StartTimeZone
          - EndDateTime
          - EndTimeZone
  - where:
      model-name: MicrosoftGraphDrive
    set:
      format-table:
        properties:
          - Id
          - Name
          - DriveType
          - CreatedDateTime
  - where:
      model-name: MicrosoftGraphDriveItem
    set:
      format-table:
        properties:
          - Id
          - Name
          - WebUrl
          - FolderChildCount
          - Size
          - CreatedDateTime
  - where:
      model-name: MicrosoftGraphList
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - Name
          - WebUrl
          - CreatedDateTime
  - where:
      model-name: MicrosoftGraphSite
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - Name
          - SiteCollectionHostname
          - WebUrl
  - where:
      model-name: MicrosoftGraphGroup
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - Description
          - GroupTypes
          - AccessType
  - where:
      model-name: MicrosoftGraphTeam
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - Description
          - IsArchived
  - where:
      model-name: MicrosoftGraphMessage
    set:
      format-table:
        properties:
          - Id
          - Subject
          - FromEmailAddressAddress
          - ReceivedDateTime
          - BodyContentType
          - hasAttachments
  - where:
      model-name: MicrosoftGraphNotebook
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - CreatedDateTime
          - IsShared
          - IsDefault
  - where:
      model-name: MicrosoftGraphSectionGroup
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - CreatedDateTime
          - ParentNotebookDisplayName
          - IsDefault
  - where:
      model-name: MicrosoftGraphConversation
    set:
      format-table:
        properties:
          - Id
          - Topic
          - UniqueSenders
          - HasAttachments
          - Threads
          - LastDeliveredDateTime
  - where:
      model-name: MicrosoftGraphConversationThread
    set:
      format-table:
        properties:
          - Id
          - Topic
          - UniqueSenders
          - HasAttachments
          - Posts
          - LastDeliveredDateTime
  - where:
      model-name: MicrosoftGraphPost
    set:
      format-table:
        properties:
          - Id
          - SenderEmailAddressAddress
          - BodyContentType
          - HasAttachments
          - ReceivedDateTime
  - where:
      model-name: MicrosoftGraphDirectoryObject
    set:
      format-table:
        properties:
          - Id
          - DeletedDateTime
  - where:
      model-name: MicrosoftGraphPlace
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - AddressCity
          - Phone
  - where:
      model-name: MicrosoftGraphPlannerTask
    set:
      format-table:
        properties:
          - Id
          - PlanId
          - BucketId
          - Title
          - Priority
          - StartDateTime
          - CompletedDateTime
          - PercentComplete
  - where:
      model-name: MicrosoftGraphPlannerPlan
    set:
      format-table:
        properties:
          - Id
          - Title
          - Owner
          - CreatedDateTime
  - where:
      model-name: MicrosoftGraphPlannerPlanDetails
    set:
      format-table:
        properties:
          - Id
          - CategoryDescriptions
          - SharedWith
          - ContextDetails
  - where:
      model-name: MicrosoftGraphSchemaExtension
    set:
      format-table:
        properties:
          - Id
          - Description
          - Properties
          - TargetTypes
          - Status
          - Owner
# Modify OpenAPI doc - Add suffix 'fn' to Sites.Functions cmdlets to avoid duplicates.
  - from: Sites.Functions.yml
    where: $.paths.*
    transform: $.get.operationId = `${$.get.operationId}Fn`
# GroupMemberOf (Groups.DirectoryObject)
  - where:
      verb: Get
      subject: GroupMember
      variant: Get1
    set:
      subject: GroupMemberOf
  - where:
      verb: Get
      subject: GroupMember
      variant: List
    set:
      subject: GroupMemberOf
  - where:
      verb: Get
      subject: GroupMember
      variant: GetViaIdentity1
    set:
      subject: GroupMemberOf
# GroupMemberWithLicenseError (Groups.DirectoryObject)
  - where:
      verb: Get
      subject: GroupMember
      variant: Get
    set:
      subject: GroupMemberWithLicenseError
  - where:
      verb: Get
      subject: GroupMember
      variant: List2
    set:
      subject: GroupMemberWithLicenseError
  - where:
      verb: Get
      subject: GroupMember
      variant: GetViaIdentity
    set:
      subject: GroupMemberWithLicenseError
# GroupTransitiveMemberOf (Groups.DirectoryObject)
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: List
    set:
      subject: GroupTransitiveMemberOf
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: Get
    set:
      subject: GroupTransitiveMemberOf
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: GetViaIdentity
    set:
      subject: GroupTransitiveMemberOf
# RemoveSite (Sites.Actions)
  - where:
      verb: Remove
      subject: Site
      variant: Remove
    hide: true
  - where:
      verb: Remove
      subject: Site
      variant: RemoveExpanded
    hide: true
# GetSite (Sites.Site)
  - where:
      verb: Get
      subject: Site
      variant: Get1
    set:
      subject: SubSite
  - where:
      verb: Get
      subject: Site
      variant: List1
    set:
      subject: SubSite
  - where:
      verb: Get
      subject: Site
      variant: GetViaIdentity1
    set:
      subject: SubSite
# NewSite (Sites.Site)
  - where:
      verb: New
      subject: Site
      variant: Create1
    set:
      subject: SubSite
  - where:
      verb: New
      subject: Site
      variant: CreateExpanded1
    set:
      subject: SubSite
  - where:
      verb: New
      subject: Site
      variant: CreateViaIdentity
    set:
      subject: SubSite
  - where:
      verb: New
      subject: Site
      variant: CreateViaIdentityExpanded
    set:
      subject: SubSite
# GetReportTenantSecureScore (Reports)
  - where:
      verb: Get
      subject: ReportTenantSecureScore
      variant: GetViaIdentity
    remove: true