# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Generates a release build artifact (nuget) from HEAD of master for V1.0 Graph workload modules.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/v1.0/*
    - config/ModulesMapping.jsonc

pr: none

variables:
  MODULE_PREFIX: 'Microsoft.Graph'
  WORKLOAD_MODULE_PATH: 'src\v1.0\'
  GRAPH_VERSION: 'v1.0'
  AUTH_MODULE_PATH: 'src\Authentication\Authentication\bin\'
  AUTH_MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'

jobs:
- job: MSGraphPSSDKGeneration
  displayName: MS Graph PS SDK v1.0 Generation
  timeoutInMinutes: 300
  pool:
    name: Microsoft Graph
    demands: 'Agent.Name -equals Local-Agent'
  
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
     debugMode: false
  
  - task: Npm@1
    displayName: 'Install AutoRest'
    inputs:
      command: 'custom'
      customCommand: 'install -g @autorest/autorest@3.0.6114'
  
  - task: PowerShell@2
    displayName: 'Build Auth Modules'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/BuildModule.ps1'
      arguments: '-Module "Authentication" -ModulePrefix $(MODULE_PREFIX) -ModuleVersion $(Module_Version) -EnableSigning'
      pwsh: true
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL Strong Name (Graph Auth Module)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: $(AUTH_MODULE_DLL_PATTERN)
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameSign",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL CodeSigning (Graph Auth Module)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: $(AUTH_MODULE_DLL_PATTERN)
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: PowerShell@2
    displayName: 'Generate and Build Graph Resource Modules'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateModules.ps1'
      arguments: '-RepositoryName $(Repository_Name) -RepositoryApiKey $(Api_Key) -ModuleVersion $(Module_Version) -ArtifactsLocation $(Build.ArtifactStagingDirectory)\$(GRAPH_VERSION)\ -UseLocalDoc -Build -EnableSigning'
      pwsh: true
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL Strong Name (Graph Resource Modules)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(WORKLOAD_MODULE_PATH)
      Pattern: '$(MODULE_PREFIX).*.private.dll'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameSign",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL CodeSigning (Graph Resource Module)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(WORKLOAD_MODULE_PATH)
      Pattern: '$(MODULE_PREFIX).*.private.dll, $(MODULE_PREFIX).*.psm1, $(MODULE_PREFIX).*.format.ps1xml, *.ps1'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 100
  
  - task: PowerShell@2
    displayName: 'Pack Modules'
    inputs:
      targetType: 'inline'
      script: |
        $ModuleMappingConfigPath = "$(System.DefaultWorkingDirectory)/config/ModulesMapping.jsonc"
        [HashTable] $ModuleMapping = Get-Content $ModuleMappingConfigPath | ConvertFrom-Json -AsHashTable
        $ModuleMapping.Keys | ForEach-Object {
            $ModuleName = $_
            $ModuleProjectDir = "$(System.DefaultWorkingDirectory)/src/$(GRAPH_VERSION)/$ModuleName/$ModuleName"
            & $(System.DefaultWorkingDirectory)/tools/PackModule.ps1 -Module $ModuleName -GraphVersion $(GRAPH_VERSION) -ArtifactsLocation $(Build.ArtifactStagingDirectory)\$(GRAPH_VERSION)\
        }
      pwsh: true
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP NuGet CodeSigning'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: '$(Build.ArtifactStagingDirectory)\$(GRAPH_VERSION)\'
      Pattern: '*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
            [
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetSign",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
      SessionTimeout: 20
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact V1.0 Modules
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(GRAPH_VERSION)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  
  - script: |
      echo V1.0 modules PR validation complete.
    displayName: 'Complete'