# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Validate pull requests to master and dev branches for auth module.
pr:
  branches:
    include:
    - dev
    - master
  paths:
    include:
    - src/Authentication/*

trigger: none

pool:
  name: Microsoft Graph
  demands: 'Agent.Name -equals Local-Agent'

steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: 'Run CredScan'
  inputs:
    debugMode: false

- task: PowerShell@2
  displayName: 'Generate and Build Auth Module'
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateAuthenticationModule.ps1'
    arguments: '-RepositoryName $(Repository_Name) -RepositoryApiKey $(Api_Key) -ModuleVersion $(Module_Version) -ArtifactsLocation $(Build.ArtifactStagingDirectory) -Build'
    pwsh: true

- script: |
    echo Auth module PR validation complete.
  displayName: 'Complete'