# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pool: MsGraphDevXAzureAgents

variables:
  Branch: "test/WeeklyOpenApiDocsDownload" #TODO: Remove test data.
  BaseBranch: "features/WeeklyReleaseUpdate" #TODO: Remove test data.
trigger: none
pr: none
schedules:
  - cron: "16 57 * * *" # TODO: Remove test data.
    # - cron: "0 12 * * WED" # Run every wednesday at noon UTC
    displayName: "Weekly PS SDK generation"
    branches:
      include:
        - dev
        - po/* #TODO: Remove test data.
        - features/* #TODO: Remove test data.
    always: true

stages:
  - stage: DownloadOpenAPIDocs
    displayName: Download OpenAPI docs
    jobs:
      - template: common-templates/download-openapi-docs.yml
        parameters:
          Branch: $(Branch)
          BaseBranch: $(BaseBranch)

  - stage: GenerateServiceModules
    displayName: Generate service modules
    jobs:
      - template: generation-templates/generate-service-modules.yml
        parameters:
          ModulesToGenerate: $[ stageDependencies.DownloadOpenAPIDocs.GetLatestDocs.outputs['OpenAPIDocDiff.ModulesWithChanges'] ]
          Branch: $[ stageDependencies.DownloadOpenAPIDocs.GetLatestDocs.outputs['ComputeBranch.WeeklyBranch'] ]
          AuthModulePath: "src/Authentication/Authentication/bin/"
          AuthModuleDllPattern: "Microsoft.Graph.Authentication.dll"
          ServiceModulePath: "src/"
          ModulePrefix: "Microsoft.Graph"
          EnableSigning: true
          PublishToFeed: false
  # Git diff on download OpenAPI docs. Store changed modules in a variable.
  # Commit downloaded docs.
  # If modules change, bump their minor and meta-module version.
  # Generate changed modules + run tests.
  # Commit generated files to weekly branch.
  # Create PR to dev
